---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: certalert
spec:
  selector:
    matchLabels:
      app: certalert
  template:
    metadata:
      labels:
        app: certalert
    spec:
      containers:
        - name: certalert
          image: ghcr.io/containeroo/certalert:latest
          ports:
            - name: http
              containerPort: 8080
          args:
            - serve
            - --config=/config/config.yaml
            - --listen-address=0.0.0.0:8080
          envFrom:
            - secretRef:
                name: certalert-password-envs
          volumeMounts:
            - name: config
              mountPath: /config
            - name: transfer
              mountPath: /transfer
            - name: certalert-password-file
              mountPath: /certs/certalert.passwords
              subPath: certalert.passwords
            - name: jks-broken-certificate
              mountPath: /certs/jks/broken.jks
              subPath: broken.jks
            - name: jks-regular-certificate
              mountPath: /certs/jks/regular.jks
              subPath: regular.jks
            - name: jks-chain-certificate
              mountPath: /certs/jks/chain.jks
              subPath: chain.jks
            - name: p12-with-password-certificate
              mountPath: /certs/p12/with_password.p12
              subPath: with_password.p12
            - name: p12-without-password-certificate
              mountPath: /certs/p12/without_password.p12
              subPath: without_password.p12
            - name: p12-chain-certificate
              mountPath: /certs/p12/chain.p12
              subPath: chain.p12
            - name: pem-broken-certificate
              mountPath: /certs/pem/broken.pem
              subPath: broken.pem
            - name: pem-with-password-certificate
              mountPath: /certs/pem/with_password.pem
              subPath: with_password.pem
            - name: pem-without-password-certificate
              mountPath: /certs/pem/without_password.pem
              subPath: without_password.pem
            - name: pem-chain-certificate
              mountPath: /certs/pem/chain.pem
              subPath: chain.pem
            - name: pem-chain-certificate-password
              mountPath: /certs/pem/chain.password
              subPath: chain.password
          resources: {}
      volumes:
        - name: config
          configMap:
            name: certalert-config
        - name: transfer
          emptyDir: {}
        - name: certalert-password-file
          secret:
            secretName: certalert-password-file
        - name: jks-broken-certificate
          configMap:
            name: jks-broken-certificate
        - name: jks-regular-certificate
          configMap:
            name: jks-regular-certificate
        - name: jks-chain-certificate
          configMap:
            name: jks-chain-certificate
        - name: p12-with-password-certificate
          configMap:
            name: p12-with-password-certificate
        - name: p12-without-password-certificate
          configMap:
            name: p12-without-password-certificate
        - name: p12-chain-certificate
          configMap:
            name: p12-chain-certificate
        - name: pem-broken-certificate
          configMap:
            name: pem-broken-certificate
        - name: pem-with-password-certificate
          configMap:
            name: pem-with-password-certificate
        - name: pem-without-password-certificate
          configMap:
            name: pem-without-password-certificate
        - name: pem-chain-certificate
          configMap:
            name: pem-chain-certificate
        - name: pem-chain-certificate-password
          secret:
            secretName: pem-chain-certificate-password
