---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: certalert
spec:
  template:
    spec:
      initContainers:
        - name: crt-makr
          image: openjdk:11
          command: ["/bin/bash"]
          args:
            - -c
            - "/tmp/crt-makr.sh /jks /transfer"
          envFrom:
            - secretRef:
                name: certalert-password-envs
          volumeMounts:
            - name: crt-makr
              mountPath: /tmp/crt-makr.sh
              subPath: crt-makr.sh
            - name: transfer
              mountPath: /transfer
            - name: certs
              mountPath: /jks
      volumes:
        - name: crt-makr
          configMap:
            name: crt-makr
            defaultMode: 0755
        - name: certs
          configMap:
            name: additional-jks-certs
            defaultMode: 0644
