---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: certalert
  namespace: monitoring
  labels:
    app: certalert
spec:
  jobLabel: certalert
  namespaceSelector:
    matchNames:
      - certalert
  selector:
    matchLabels:
      app: certalert
  endpoints:
    - interval: 60m
      port: http
