---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - v1_configmap_jks-broken-certificate.yaml
  - v1_configmap_jks-chain-certificate.yaml
  - v1_configmap_jks-regular-certificate.yaml
  - v1_configmap_p12-broken-certificate.yaml
  - v1_configmap_p12-chain-certificate.yaml
  - v1_configmap_p12-with-password-certificate.yaml
  - v1_configmap_p12-without-password-certificate.yaml
  - v1_configmap_pem-broken-certificate.yaml
  - v1_configmap_pem-chain-certificate.yaml
  - v1_configmap_pem-with-password-certificate.yaml
  - v1_configmap_pem-without-password-certificate.yaml
